-- =============================================================================
-- LibraryLab — Database Schema Initialization + Seed Data
-- Executed automatically by PostgreSQL on first container startup
-- via docker-entrypoint-initdb.d
-- =============================================================================

-- =============================================================================
-- SCHEMA CREATION
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Catalog Bounded Context
-- -----------------------------------------------------------------------------

CREATE TABLE categories (
                            category_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name            VARCHAR(100)    NOT NULL UNIQUE,
                            description     VARCHAR(500),
                            version         BIGINT          NOT NULL DEFAULT 0,
                            created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                            updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE books (
                       book_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       isbn            VARCHAR(17)     NOT NULL UNIQUE,
                       title           VARCHAR(255)    NOT NULL,
                       author          VARCHAR(255)    NOT NULL,
                       publisher       VARCHAR(100),
                       publicationdate DATE,
                       totalcopies     INTEGER         NOT NULL DEFAULT 1,
                       availablecopies INTEGER         NOT NULL DEFAULT 1,
                       status          VARCHAR(20)     NOT NULL DEFAULT 'AVAILABLE',
                       category_id     BIGINT          NOT NULL REFERENCES categories(category_id),
                       version         BIGINT          NOT NULL DEFAULT 0,
                       created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                       updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Membership Bounded Context
-- -----------------------------------------------------------------------------

CREATE TABLE members (
                         member_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         membership_number   VARCHAR(20)     NOT NULL UNIQUE,
                         first_name          VARCHAR(100)    NOT NULL,
                         last_name           VARCHAR(100)    NOT NULL,
                         email               VARCHAR(255)    NOT NULL UNIQUE,
                         phone               VARCHAR(20),
                         address             VARCHAR(255),
                         registration_date   DATE            NOT NULL DEFAULT CURRENT_DATE,
                         expiration_date     DATE,
                         status              VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
                         active_loans        INTEGER         NOT NULL DEFAULT 0,
                         max_loans           INTEGER         NOT NULL DEFAULT 5,
                         version             BIGINT          NOT NULL DEFAULT 0,
                         created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                         updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Lending Bounded Context
-- -----------------------------------------------------------------------------

CREATE TABLE loans (
                       loan_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       book_id         BIGINT          NOT NULL REFERENCES books(book_id),
                       member_id       BIGINT          NOT NULL REFERENCES members(member_id),
                       loan_date       DATE            NOT NULL DEFAULT CURRENT_DATE,
                       due_date        DATE            NOT NULL,
                       return_date     DATE,
                       status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
                       renewal_count   INTEGER         NOT NULL DEFAULT 0,
                       notes           VARCHAR(500),
                       version         BIGINT          NOT NULL DEFAULT 0,
                       created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                       updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Indexes for common query patterns
-- -----------------------------------------------------------------------------

CREATE INDEX idx_books_category   ON books(category_id);
CREATE INDEX idx_books_status     ON books(status);
CREATE INDEX idx_loans_book       ON loans(book_id);
CREATE INDEX idx_loans_member     ON loans(member_id);
CREATE INDEX idx_loans_status     ON loans(status);
CREATE INDEX idx_loans_due_date   ON loans(due_date);
CREATE INDEX idx_members_status   ON members(status);
CREATE INDEX idx_members_email    ON members(email);


-- =============================================================================
-- SEED DATA
-- =============================================================================
-- Data consistency rules enforced in this seed:
--
--   availablecopies = totalcopies - (ACTIVE + OVERDUE loans for that book)
--   active_loans    = count of ACTIVE + OVERDUE loans for that member
--   RETURNED loans  → return_date IS NOT NULL
--   ACTIVE loans    → return_date IS NULL, due_date in the future
--   OVERDUE loans   → return_date IS NULL, due_date in the past
--   LOST loans      → return_date IS NULL
--
-- Dates use CURRENT_DATE-relative expressions so the data stays
-- realistic regardless of when the container is first started.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Categories (10 records)
-- IDs will be 1..10 (GENERATED BY DEFAULT AS IDENTITY)
-- -----------------------------------------------------------------------------

INSERT INTO categories (name, description) VALUES
                                               ('Programming',          'Books about software development, coding practices, and programming languages'),
                                               ('Computer Science',     'Foundational topics including algorithms, data structures, and computational theory'),
                                               ('Software Engineering', 'Software design, architecture, project management, and development methodologies'),
                                               ('Databases',            'Relational databases, NoSQL, query optimization, and data modeling'),
                                               ('DevOps',               'Continuous integration, deployment, containerization, and infrastructure automation'),
                                               ('Networking',           'Computer networks, protocols, security, and distributed systems'),
                                               ('Artificial Intelligence', 'Machine learning, deep learning, natural language processing, and AI fundamentals'),
                                               ('Operating Systems',    'OS internals, Linux administration, kernel development, and system programming'),
                                               ('Web Development',      'Frontend and backend web technologies, frameworks, and web architecture'),
                                               ('Science Fiction',      'Classic and modern science fiction literature');

-- -----------------------------------------------------------------------------
-- Books (20 records)
-- IDs will be 1..20
--
-- availablecopies already accounts for the ACTIVE/OVERDUE loans below:
--   Book 1:  3 total, 1 active loan  → 2 available
--   Book 2:  2 total, 1 active loan  → 1 available
--   Book 3:  4 total, 1 active loan  → 3 available
--   Book 5:  3 total, 1 overdue loan → 2 available
--   Book 7:  2 total, 1 active loan  → 1 available
--   Book 8:  3 total, 1 active loan  → 2 available
--   Book 10: 2 total, 1 active loan  → 1 available
--   Book 12: 3 total, 1 overdue loan → 2 available
--   Book 14: 2 total, 1 active loan  → 1 available
--   Book 16: 4 total, 1 active loan  → 3 available
--   All others: availablecopies = totalcopies
-- -----------------------------------------------------------------------------

INSERT INTO books (isbn, title, author, publisher, publicationdate, totalcopies, availablecopies, status, category_id) VALUES
                                                                                                                           ('978-0134685991', 'Effective Java',                         'Joshua Bloch',         'Addison-Wesley',   '2018-01-06', 3, 2, 'AVAILABLE', 1),
                                                                                                                           ('978-0596009205', 'Head First Design Patterns',             'Eric Freeman',         'O''Reilly Media',  '2020-12-29', 2, 1, 'AVAILABLE', 1),
                                                                                                                           ('978-0132350884', 'Clean Code',                             'Robert C. Martin',     'Prentice Hall',    '2008-08-01', 4, 3, 'AVAILABLE', 3),
                                                                                                                           ('978-0201633610', 'Design Patterns',                        'Erich Gamma',          'Addison-Wesley',   '1994-10-31', 2, 2, 'AVAILABLE', 3),
                                                                                                                           ('978-0137081073', 'The Clean Coder',                        'Robert C. Martin',     'Prentice Hall',    '2011-05-13', 3, 2, 'AVAILABLE', 3),
                                                                                                                           ('978-0596007126', 'Head First Object-Oriented Analysis',    'Brett McLaughlin',     'O''Reilly Media',  '2006-11-27', 2, 2, 'AVAILABLE', 3),
                                                                                                                           ('978-0321125217', 'Domain-Driven Design',                   'Eric Evans',           'Addison-Wesley',   '2003-08-30', 2, 1, 'AVAILABLE', 3),
                                                                                                                           ('978-0135957059', 'The Pragmatic Programmer',               'David Thomas',         'Addison-Wesley',   '2019-09-23', 3, 2, 'AVAILABLE', 3),
                                                                                                                           ('978-0262033848', 'Introduction to Algorithms',             'Thomas H. Cormen',     'MIT Press',        '2009-07-31', 3, 3, 'AVAILABLE', 2),
                                                                                                                           ('978-0131103627', 'The C Programming Language',             'Brian W. Kernighan',   'Prentice Hall',    '1988-03-22', 2, 1, 'AVAILABLE', 1),
                                                                                                                           ('978-1491950357', 'Building Microservices',                 'Sam Newman',           'O''Reilly Media',  '2021-08-17', 3, 3, 'AVAILABLE', 3),
                                                                                                                           ('978-1492078005', 'Learning SQL',                           'Alan Beaulieu',        'O''Reilly Media',  '2020-03-10', 3, 2, 'AVAILABLE', 4),
                                                                                                                           ('978-1492057611', 'Kubernetes Up & Running',                'Brendan Burns',        'O''Reilly Media',  '2022-08-23', 3, 3, 'AVAILABLE', 5),
                                                                                                                           ('978-0131872486', 'TCP/IP Illustrated',                     'Kevin R. Fall',        'Addison-Wesley',   '2011-11-18', 2, 1, 'AVAILABLE', 6),
                                                                                                                           ('978-0262035613', 'Deep Learning',                          'Ian Goodfellow',       'MIT Press',        '2016-11-18', 2, 2, 'AVAILABLE', 7),
                                                                                                                           ('978-0131103628', 'Operating System Concepts',              'Abraham Silberschatz', 'Wiley',            '2018-05-04', 4, 3, 'AVAILABLE', 8),
                                                                                                                           ('978-1491952023', 'JavaScript: The Definitive Guide',       'David Flanagan',       'O''Reilly Media',  '2020-05-14', 2, 2, 'AVAILABLE', 9),
                                                                                                                           ('978-0441013593', 'Dune',                                   'Frank Herbert',        'Ace Books',        '1965-08-01', 3, 3, 'AVAILABLE', 10),
                                                                                                                           ('978-0062316097', 'Sapiens',                                'Yuval Noah Harari',    'Harper Perennial', '2015-02-10', 2, 2, 'AVAILABLE', 2),
                                                                                                                           ('978-0596517748', 'The Art of Agile Development',           'James Shore',          'O''Reilly Media',  '2021-10-19', 3, 3, 'AVAILABLE', 3);

-- -----------------------------------------------------------------------------
-- Members (20 records)
-- IDs will be 1..20
--
-- active_loans matches the count of ACTIVE/OVERDUE loans per member:
--   Member 1:  2 (loans on books 1 and 3)
--   Member 2:  1 (loan on book 2)
--   Member 3:  1 (overdue loan on book 5)
--   Member 5:  1 (loan on book 7)
--   Member 7:  1 (loan on book 8)
--   Member 9:  1 (loan on book 10)
--   Member 10: 1 (overdue loan on book 12)
--   Member 12: 1 (loan on book 14)
--   Member 15: 1 (loan on book 16)
--   All others: 0
--
-- Members 16, 17, 19 demonstrate non-ACTIVE statuses:
--   16 → EXPIRED   (expiration_date in the past)
--   17 → SUSPENDED
--   19 → INACTIVE
-- -----------------------------------------------------------------------------

INSERT INTO members (membership_number, first_name, last_name, email, phone, address, registration_date, expiration_date, status, active_loans, max_loans) VALUES
                                                                                                                                                               ('MEM-2025-001', 'Carlos',    'Méndez',     'carlos.mendez@email.com',      '809-555-0101', 'Calle El Conde 45, Zona Colonial',        '2025-01-15', '2026-01-15', 'ACTIVE',    2, 5),
                                                                                                                                                               ('MEM-2025-002', 'María',     'Rodríguez',  'maria.rodriguez@email.com',    '809-555-0102', 'Av. Winston Churchill 89, Piantini',      '2025-02-20', '2026-02-20', 'ACTIVE',    1, 5),
                                                                                                                                                               ('MEM-2025-003', 'José',      'Pérez',      'jose.perez@email.com',         '809-555-0103', 'Calle Duarte 12, Gazcue',                 '2025-01-10', '2026-01-10', 'ACTIVE',    1, 5),
                                                                                                                                                               ('MEM-2025-004', 'Ana',       'García',     'ana.garcia@email.com',         '809-555-0104', 'Av. Abraham Lincoln 502, Naco',           '2025-03-05', '2026-03-05', 'ACTIVE',    0, 5),
                                                                                                                                                               ('MEM-2025-005', 'Luis',      'Martínez',   'luis.martinez@email.com',      '809-555-0105', 'Calle José Contreras 78, Bella Vista',    '2025-02-01', '2026-02-01', 'ACTIVE',    1, 5),
                                                                                                                                                               ('MEM-2025-006', 'Carmen',    'Sánchez',    'carmen.sanchez@email.com',     '809-555-0106', 'Av. 27 de Febrero 340, Evaristo Morales', '2025-04-10', '2026-04-10', 'ACTIVE',    0, 5),
                                                                                                                                                               ('MEM-2025-007', 'Pedro',     'Ramírez',    'pedro.ramirez@email.com',      '809-555-0107', 'Calle Fantino Falco 15, Serrallés',       '2025-01-20', '2026-01-20', 'ACTIVE',    1, 5),
                                                                                                                                                               ('MEM-2025-008', 'Laura',     'Torres',     'laura.torres@email.com',       '809-555-0108', 'Av. Tiradentes 22, Naco',                 '2025-03-15', '2026-03-15', 'ACTIVE',    0, 5),
                                                                                                                                                               ('MEM-2025-009', 'Miguel',    'Hernández',  'miguel.hernandez@email.com',   '809-555-0109', 'Calle Padre Billini 56, Ciudad Colonial', '2025-05-01', '2026-05-01', 'ACTIVE',    1, 5),
                                                                                                                                                               ('MEM-2025-010', 'Sofía',     'Díaz',       'sofia.diaz@email.com',         '809-555-0110', 'Av. Máximo Gómez 100, La Esperilla',      '2025-02-25', '2026-02-25', 'ACTIVE',    1, 5),
                                                                                                                                                               ('MEM-2025-011', 'Rafael',    'Morales',    'rafael.morales@email.com',     '809-555-0111', 'Calle Santiago 34, Gazcue',                '2025-06-01', '2026-06-01', 'ACTIVE',    0, 5),
                                                                                                                                                               ('MEM-2025-012', 'Isabella',  'Cruz',       'isabella.cruz@email.com',      '809-555-0112', 'Av. Independencia 205, Centro',           '2025-04-20', '2026-04-20', 'ACTIVE',    1, 5),
                                                                                                                                                               ('MEM-2025-013', 'Fernando',  'Reyes',      'fernando.reyes@email.com',     '809-555-0113', 'Calle Las Damas 8, Zona Colonial',        '2025-01-05', '2026-01-05', 'ACTIVE',    0, 5),
                                                                                                                                                               ('MEM-2025-014', 'Valentina', 'Castillo',   'valentina.castillo@email.com', '809-555-0114', 'Av. Lope de Vega 67, Naco',               '2025-05-15', '2026-05-15', 'ACTIVE',    0, 5),
                                                                                                                                                               ('MEM-2025-015', 'Alejandro', 'Vargas',     'alejandro.vargas@email.com',   '809-555-0115', 'Calle El Recodo 90, Bella Vista',         '2025-03-01', '2026-03-01', 'ACTIVE',    1, 5),
                                                                                                                                                               ('MEM-2024-016', 'Gabriela',  'Núñez',      'gabriela.nunez@email.com',     '809-555-0116', 'Av. Sarasota 55, Piantini',               '2024-06-10', '2025-06-10', 'EXPIRED',   0, 5),
                                                                                                                                                               ('MEM-2024-017', 'Roberto',   'Almonte',    'roberto.almonte@email.com',    '809-555-0117', 'Calle Arzobispo Meriño 33, Colonial',     '2024-08-20', '2025-08-20', 'SUSPENDED', 0, 5),
                                                                                                                                                               ('MEM-2025-018', 'Patricia',  'Bautista',   'patricia.bautista@email.com',  '809-555-0118', 'Av. Bolívar 180, Gazcue',                 '2025-07-01', '2026-07-01', 'ACTIVE',    0, 5),
                                                                                                                                                               ('MEM-2024-019', 'Andrés',    'Peña',       'andres.pena@email.com',        '809-555-0119', 'Calle Isabel la Católica 5, Colonial',    '2024-03-15', '2025-03-15', 'INACTIVE',  0, 5),
                                                                                                                                                               ('MEM-2025-020', 'Daniela',   'Mejía',      'daniela.mejia@email.com',      '809-555-0120', 'Av. Pasteur 44, La Esperilla',            '2025-08-10', '2026-08-10', 'ACTIVE',    0, 5);

-- -----------------------------------------------------------------------------
-- Loans (20 records)
-- IDs will be 1..20
--
-- Status distribution:
--   10 ACTIVE   — currently borrowed, due_date in the future
--    2 OVERDUE  — past due_date, not returned
--    7 RETURNED — completed, return_date set
--    1 LOST     — permanently lost
--
-- Dates are relative to CURRENT_DATE so the data is always realistic.
-- -----------------------------------------------------------------------------

INSERT INTO loans (book_id, member_id, loan_date, due_date, return_date, status, renewal_count, notes) VALUES
                                                                                                           -- === ACTIVE loans (due in the future, no return_date) ===
                                                                                                           (1,  1,  CURRENT_DATE - INTERVAL '5 days',  CURRENT_DATE + INTERVAL '9 days',  NULL, 'ACTIVE',  0, NULL),
                                                                                                           (2,  2,  CURRENT_DATE - INTERVAL '3 days',  CURRENT_DATE + INTERVAL '11 days', NULL, 'ACTIVE',  0, NULL),
                                                                                                           (3,  1,  CURRENT_DATE - INTERVAL '4 days',  CURRENT_DATE + INTERVAL '10 days', NULL, 'ACTIVE',  0, NULL),
                                                                                                           (7,  5,  CURRENT_DATE - INTERVAL '7 days',  CURRENT_DATE + INTERVAL '7 days',  NULL, 'ACTIVE',  0, 'Requested by professor for course'),
                                                                                                           (8,  7,  CURRENT_DATE - INTERVAL '10 days', CURRENT_DATE + INTERVAL '4 days',  NULL, 'ACTIVE',  0, NULL),
                                                                                                           (10, 9,  CURRENT_DATE - INTERVAL '2 days',  CURRENT_DATE + INTERVAL '12 days', NULL, 'ACTIVE',  0, NULL),
                                                                                                           (14, 12, CURRENT_DATE - INTERVAL '6 days',  CURRENT_DATE + INTERVAL '8 days',  NULL, 'ACTIVE',  0, NULL),
                                                                                                           (16, 15, CURRENT_DATE - INTERVAL '1 day',   CURRENT_DATE + INTERVAL '13 days', NULL, 'ACTIVE',  0, NULL),

                                                                                                           -- === OVERDUE loans (due_date in the past, no return_date) ===
                                                                                                           (5,  3,  CURRENT_DATE - INTERVAL '29 days', CURRENT_DATE - INTERVAL '15 days', NULL, 'OVERDUE', 0, 'First overdue notice sent'),
                                                                                                           (12, 10, CURRENT_DATE - INTERVAL '21 days', CURRENT_DATE - INTERVAL '7 days',  NULL, 'OVERDUE', 1, 'Renewed once, still overdue'),

                                                                                                           -- === RETURNED loans (return_date set) ===
                                                                                                           (9,  4,  CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE - INTERVAL '16 days', CURRENT_DATE - INTERVAL '18 days', 'RETURNED', 0, NULL),
                                                                                                           (18, 6,  CURRENT_DATE - INTERVAL '25 days', CURRENT_DATE - INTERVAL '11 days', CURRENT_DATE - INTERVAL '12 days', 'RETURNED', 0, 'Member enjoyed the book'),
                                                                                                           (11, 8,  CURRENT_DATE - INTERVAL '40 days', CURRENT_DATE - INTERVAL '12 days', CURRENT_DATE - INTERVAL '13 days', 'RETURNED', 1, 'Renewed once before returning'),
                                                                                                           (15, 11, CURRENT_DATE - INTERVAL '35 days', CURRENT_DATE - INTERVAL '21 days', CURRENT_DATE - INTERVAL '22 days', 'RETURNED', 0, NULL),
                                                                                                           (17, 13, CURRENT_DATE - INTERVAL '20 days', CURRENT_DATE - INTERVAL '6 days',  CURRENT_DATE - INTERVAL '8 days',  'RETURNED', 0, NULL),
                                                                                                           (19, 14, CURRENT_DATE - INTERVAL '28 days', CURRENT_DATE - INTERVAL '14 days', CURRENT_DATE - INTERVAL '15 days', 'RETURNED', 0, 'Excellent condition on return'),
                                                                                                           (6,  18, CURRENT_DATE - INTERVAL '18 days', CURRENT_DATE - INTERVAL '4 days',  CURRENT_DATE - INTERVAL '5 days',  'RETURNED', 0, NULL),
                                                                                                           (13, 20, CURRENT_DATE - INTERVAL '22 days', CURRENT_DATE - INTERVAL '8 days',  CURRENT_DATE - INTERVAL '9 days',  'RETURNED', 0, 'Returned in good condition'),
                                                                                                           (20, 4,  CURRENT_DATE - INTERVAL '15 days', CURRENT_DATE - INTERVAL '1 day',   CURRENT_DATE - INTERVAL '2 days',  'RETURNED', 0, NULL),

                                                                                                           -- === LOST loan ===
                                                                                                           (4,  17, CURRENT_DATE - INTERVAL '60 days', CURRENT_DATE - INTERVAL '46 days', NULL, 'LOST', 0, 'Book reported lost by suspended member');