-- =============================================================================
-- LibraryLab — Database Schema Initialization
-- Executed automatically by PostgreSQL on first container startup
-- via docker-entrypoint-initdb.d
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Catalog Bounded Context
-- -----------------------------------------------------------------------------

CREATE TABLE categories (
    category_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL UNIQUE,
    description     VARCHAR(500),
    version         BIGINT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE books (
    book_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn            VARCHAR(17)     NOT NULL UNIQUE,
    title           VARCHAR(255)    NOT NULL,
    author          VARCHAR(255)    NOT NULL,
    publisher       VARCHAR(100),
    publicationdate DATE,
    totalcopies     INTEGER         NOT NULL DEFAULT 1,
    availablecopies INTEGER         NOT NULL DEFAULT 1,
    status          VARCHAR(20)     NOT NULL DEFAULT 'AVAILABLE',
    category_id     BIGINT          NOT NULL REFERENCES categories(category_id),
    version         BIGINT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Membership Bounded Context
-- -----------------------------------------------------------------------------

CREATE TABLE members (
    member_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_number   VARCHAR(20)     NOT NULL UNIQUE,
    first_name          VARCHAR(100)    NOT NULL,
    last_name           VARCHAR(100)    NOT NULL,
    email               VARCHAR(255)    NOT NULL UNIQUE,
    phone               VARCHAR(20),
    address             VARCHAR(255),
    registration_date   DATE            NOT NULL DEFAULT CURRENT_DATE,
    expiration_date     DATE,
    status              VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    active_loans        INTEGER         NOT NULL DEFAULT 0,
    max_loans           INTEGER         NOT NULL DEFAULT 5,
    version             BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Lending Bounded Context
-- -----------------------------------------------------------------------------

CREATE TABLE loans (
    loan_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id         BIGINT          NOT NULL REFERENCES books(book_id),
    member_id       BIGINT          NOT NULL REFERENCES members(member_id),
    loan_date       DATE            NOT NULL DEFAULT CURRENT_DATE,
    due_date        DATE            NOT NULL,
    return_date     DATE,
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    renewal_count   INTEGER         NOT NULL DEFAULT 0,
    notes           VARCHAR(500),
    version         BIGINT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Indexes for common query patterns
-- -----------------------------------------------------------------------------

CREATE INDEX idx_books_category   ON books(category_id);
CREATE INDEX idx_books_status     ON books(status);
CREATE INDEX idx_loans_book       ON loans(book_id);
CREATE INDEX idx_loans_member     ON loans(member_id);
CREATE INDEX idx_loans_status     ON loans(status);
CREATE INDEX idx_loans_due_date   ON loans(due_date);
CREATE INDEX idx_members_status   ON members(status);
CREATE INDEX idx_members_email    ON members(email);
